name: Build
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Build
        run: |
          mkdir -p dist
          go build -ldflags "-X main.version=$(git describe --tags --abbrev=0)" -o dist/ttq .

      - name: Test
        run: go test -v ./...

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ttq-binaries
          path: ./dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
