name: Run ttq CLI

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-ttq:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar ttq-cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/Vavarine/tiquetaque-cli/main/install.sh | bash

      - name: Rodar ttq login
        run: |
          ttq l --email "${{ secrets.TTQ_EMAIL }}" --code "${{ secrets.TTQ_CODE }}"

      - name: Rodar ttq h
        run: |
          ttq h